### ISSUE TITLE
Update to stylelint 14

### ISSUE THREAD

**Issue by ankrut** [werk85/stylelint-config-werk85#8]
Stylint 14 is out with [breaking changes](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-14.md).

Note also that In parallel the [stylelint vscode extension](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint) (1.x and above) does not support stylelint below version 14.

**Comment by ankrut** [comment]
Regarding styled-components, there is [no customSyntax from styled-components](https://github.com/styled-components/styled-components/issues/3607) available, yet, and [processors are discouraged](https://stylelint.io/user-guide/configure/#processors) with stylelint 14.

Instead, the [postcss-css-in-js syntax](https://github.com/stylelint/postcss-css-in-js) could be used... as an intermediate solution. However, it has has [some know issues](https://github.com/stylelint/stylelint/issues/4574) and there is some chance that it [maybe will be deprecated](https://github.com/stylelint/postcss-css-in-js/issues/225) in some future.

**Comment by david-zacharias** [comment]
Mit  #10 erfolgt.
